apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopsx-app
  template:
    metadata:
      labels:
        app: devopsx-app
    spec:
      containers:
        - name: devopsx-app
          image: devopsx-2.0:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
